# Configuration file
---
patch_creator:
    # Path to folder containing the image files
    source_dir: "experiments/original/"

    # Path to folder for storing the patches
    patch_dir: experiments/patches/

    # Variation of the patching that's to be performed
    # ['tile', 'tile_annotations', 'artefact_annotations']
    function_type: 'tile'

    # Thresholds to consider
    thresholds:
        'annotations': 254  # For the annotated images
        'artefacts': 50  # For artefacts in all images
        'patch_positive': 10000  # For positive label

    # patch_size is taken as a square
    patch_size: 256


extract_features_resnet_torch:
    # Path to folder containing the image folders of patches
    patch_dir: "experiments/patches/"

    # Path to folder for storing the feature vectors
    feat_dir: "experiments/features/"


extract_features_resnet_keras:
    # Path to folder containing the image folders of patches
    patch_dir: "experiments/patches/"

    # Path to folder for storing the feature vectors
    feat_dir: "experiments/features_1/"

dataset_csv_creator:
    filename : "experiments/dataset_csv/_task_.csv"
    patch_dir : "experiments/patches/"
    feat_dir : "experiments/features/"
    annotated_dir: "experiments/annotations/original/"


splits_creator:
    label_frac : 1.0
    seed : 1
    k : 5
    val_frac : 0.15
    test_frac : 0.15

    annot_frac: 0.3  # Annotation fraction of the Training dataset
    annot_positive_frac: 1  # Fraction of annot_frac to be from positive labels


main:
    max_epochs : 200
    lr : !!float 1e-4
    label_frac : 1.0
    reg : !!float 1e-5
    seed : 1
    k : 5
    k_start : -1
    k_end : -1
    dataset_csv: "experiments/dataset_csv/fungal_vs_nonfungal.csv"
    results_dir : "experiments/results/"
    split_dir : "experiments/splits/fungal_vs_nonfungal_100"
    log_data : False
    testing : False
    early_stopping : False
    opt : 'adam'
    drop_out : False
    bag_loss : 'ce'  # ['ce', 'svm']
    model_type : 'clam_sb'  # ['clam_sb', 'clam_mb', 'mil']
    weighted_sample : False
    model_size : 'small'
    task : 'task_fungal_vs_nonfungal'

    ### CLAM specific options
    no_inst_cluster : False
    inst_loss : 'svm'  # ['svm', 'ce', None]
    subtyping : False
    bag_weight : 0.5
    B : 12

    exp_code : "exp_00"  # Experiment name
    dropout : True  # Whether to use dropout
    patch_dir : "experiments/patches/"
    dest_dir : "experiments/splits/"
    annot_dir: "experiments/annotations/patches/"
    feat_dir : "experiments/features"

    ### Alpha weight
    alpha_weight: False
    T1: 50
    T2: 150
    af: 1.0


heatmaps_creator:
    drop_out : False
    n_classes : 2
    splits : [1, 3, 5]
    model_type : "clam_sb"
    model_size : 'small'
    exp_code : "exp_00_s1"
    results_dir : "experiments/results/"

    data_dir : "experiments/original/"
    image_ext : ".tif"
    patch_dir : "experiments/patches/"
    feat_dir : "experiments/features/"

    # Only create heatmaps for selected images
    select_image : [0, 5, 10, 15, 20, 25]


draw_heatmaps:
    drop_out : False
    n_classes : 2
    splits : [1, 3, 5]
    model_type : "clam_sb"
    model_size : 'small'
    exp_code : "exp_00_s1"
    results_dir : "experiments/results/"

    data_dir : "experiments/original/"
    image_ext : ".tif"
    patch_dir : "experiments/patches/"
    feat_dir : "experiments/features/"

    patch_size : [256, 256]
    blur : [128, 128]
    alpha : 1
    beta : 0.5
    gamma : 0.0
    cmap : 'coolwarm'
    threshold : 0.5

    # Only create heatmaps for selected images
    select_image : [0, 5, 10, 15, 20, 25]
